[build]
  command = "npm run build:all"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# CORRECTION DU MIME TYPE
[[headers]]
  for = "/dist/js/*"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/dist/css/*"
  [headers.values]
    Content-Type = "text/css"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200